# Generated by Django 4.2.2 on 2023-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=232, max_length=255),
            preserve_default=False,
        ),
    ]
